Mounted at /content/drive

In [6]:
from google.colab import drive
import pandas as pd
import numpy as np
from scipy import stats


drive.mount('/content/drive')


file_path = '/content/drive/MyDrive/internship/critic_reviews.csv'
df = pd.read_csv(file_path)

print(df.head())
print(df.info())
print(df.describe())


print(df.isnull().sum())
df = df.dropna()


print(df.duplicated().sum())
df = df.drop_duplicates()


numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
df = df[(np.abs(stats.zscore(df[numerical_cols])) < 3).all(axis=1)]


cleaned_file_path = '/content/drive/MyDrive/internship/cleaned_critic_reviews.csv'
df.to_csv(cleaned_file_path, index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   reviewId creationDate      criticName            criticPageUrl reviewState  \
0   1912176   1966-07-30  Jennie Kermode  /critics/jennie-kermode       fresh
1   1895073   1998-08-21      Scott Nash      /critics/scott-nash       fresh
2     25507   2000-01-01     Roger Ebert     /critics/roger-ebert       fresh
3     25508   2000-01-01             NaN                      NaN      rotten
4     25509   2000-01-01       Joe Brown       /critics/joe-brown       fresh

   isFresh  isRotten isRtUrl  isTopCritic        publicationUrl  \
0     True     False   False        False  /critics/source/1869
1     True     False   False        False  /critics/source/1465
2     True     False   False         True    /critics/source/67
3    False      True   False         True   /critics/source/148
4     True     False   False         True   /critics/source/474

     publicationName                                          reviewUrl  \
0       Eye for Film    http://www.eyeforfilm.co.uk/reviews.php?id=7898
1  Three Movie Buffs        http://www.threemoviebuffs.com/review/blade
2  Chicago Sun-Times  http://www.rogerebert.com/reviews/the-rocketee...
3    Empire Magazine  http://www.empireonline.com/reviews/reviewcomp...
4    Washington Post  http://www.washingtonpost.com/wp-srv/style/lon...

                                               quote scoreSentiment  \
0                                                NaN       POSITIVE
1  It's stylish and fast-paced. It's also a lot o...       POSITIVE
2  You have to dial down, to return to an age of ...       POSITIVE
3        Reaches for the skies but runs out of fuel.       NEGATIVE
4  Based on a comic book, deliciously corny but n...       POSITIVE

  originalScore                               movieId
0           4/5  7602d2ab-c9bc-3439-9cd6-d3a06e81728e
1           3/4  4128b2f6-8c69-396a-a83d-0d44eb90e5f7
2           3/4  01935e47-e735-30c3-b8bd-72a9dbbcfa8a
3           2/5  01935e47-e735-30c3-b8bd-72a9dbbcfa8a
4           NaN  01935e47-e735-30c3-b8bd-72a9dbbcfa8a
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27142 entries, 0 to 27141
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   reviewId         27142 non-null  int64
 1   creationDate     27142 non-null  object
 2   criticName       27054 non-null  object
 3   criticPageUrl    27054 non-null  object
 4   reviewState      27142 non-null  object
 5   isFresh          27142 non-null  bool
 6   isRotten         27142 non-null  bool
 7   isRtUrl          26513 non-null  object
 8   isTopCritic      27142 non-null  bool
 9   publicationUrl   27142 non-null  object
 10  publicationName  27142 non-null  object
 11  reviewUrl        25077 non-null  object
 12  quote            26953 non-null  object
 13  scoreSentiment   27142 non-null  object
 14  originalScore    19413 non-null  object
 15  movieId          27142 non-null  object
dtypes: bool(3), int64(1), object(12)
memory usage: 2.8+ MB
None
           reviewId
count  2.714200e+04
mean   1.628587e+07
std    3.493963e+07
min    1.705000e+03
25%    2.082886e+06
50%    2.407968e+06
75%    2.667693e+06
max    1.029234e+08
reviewId              0
creationDate          0
criticName           88
criticPageUrl        88
reviewState           0
isFresh               0
isRotten              0
isRtUrl             629
isTopCritic           0
publicationUrl        0
publicationName       0
reviewUrl          2065
quote               189
scoreSentiment        0
originalScore      7729
movieId               0
dtype: int64
0

In [8]:
from google.colab import drive
import pandas as pd
import numpy as np
from scipy import stats


drive.mount('/content/drive')


file_path = '/content/drive/MyDrive/internship/critic_reviews.csv'
df = pd.read_csv(file_path)


print(df.head())
print(df.info())
print(df.describe())

print(df.isnull().sum())
df = df.dropna()


print(df.duplicated().sum())
df = df.drop_duplicates()


numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
df = df[(np.abs(stats.zscore(df[numerical_cols])) < 3).all(axis=1)]




cleaned_file_path = '/content/drive/MyDrive/internship/cleaned_critic_reviews.csv'
df.to_csv(cleaned_file_path, index=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   reviewId creationDate      criticName            criticPageUrl reviewState  \
0   1912176   1966-07-30  Jennie Kermode  /critics/jennie-kermode       fresh
1   1895073   1998-08-21      Scott Nash      /critics/scott-nash       fresh
2     25507   2000-01-01     Roger Ebert     /critics/roger-ebert       fresh
3     25508   2000-01-01             NaN                      NaN      rotten
4     25509   2000-01-01       Joe Brown       /critics/joe-brown       fresh

   isFresh  isRotten isRtUrl  isTopCritic        publicationUrl  \
0     True     False   False        False  /critics/source/1869
1     True     False   False        False  /critics/source/1465
2     True     False   False         True    /critics/source/67
3    False      True   False         True   /critics/source/148
4     True     False   False         True   /critics/source/474

     publicationName                                          reviewUrl  \
0       Eye for Film    http://www.eyeforfilm.co.uk/reviews.php?id=7898
1  Three Movie Buffs        http://www.threemoviebuffs.com/review/blade
2  Chicago Sun-Times  http://www.rogerebert.com/reviews/the-rocketee...
3    Empire Magazine  http://www.empireonline.com/reviews/reviewcomp...
4    Washington Post  http://www.washingtonpost.com/wp-srv/style/lon...

                                               quote scoreSentiment  \
0                                                NaN       POSITIVE
1  It's stylish and fast-paced. It's also a lot o...       POSITIVE
2  You have to dial down, to return to an age of ...       POSITIVE
3        Reaches for the skies but runs out of fuel.       NEGATIVE
4  Based on a comic book, deliciously corny but n...       POSITIVE

  originalScore                               movieId
0           4/5  7602d2ab-c9bc-3439-9cd6-d3a06e81728e
1           3/4  4128b2f6-8c69-396a-a83d-0d44eb90e5f7
2           3/4  01935e47-e735-30c3-b8bd-72a9dbbcfa8a
3           2/5  01935e47-e735-30c3-b8bd-72a9dbbcfa8a
4           NaN  01935e47-e735-30c3-b8bd-72a9dbbcfa8a
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27142 entries, 0 to 27141
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   reviewId         27142 non-null  int64
 1   creationDate     27142 non-null  object
 2   criticName       27054 non-null  object
 3   criticPageUrl    27054 non-null  object
 4   reviewState      27142 non-null  object
 5   isFresh          27142 non-null  bool
 6   isRotten         27142 non-null  bool
 7   isRtUrl          26513 non-null  object
 8   isTopCritic      27142 non-null  bool
 9   publicationUrl   27142 non-null  object
 10  publicationName  27142 non-null  object
 11  reviewUrl        25077 non-null  object
 12  quote            26953 non-null  object
 13  scoreSentiment   27142 non-null  object
 14  originalScore    19413 non-null  object
 15  movieId          27142 non-null  object
dtypes: bool(3), int64(1), object(12)
memory usage: 2.8+ MB
None
           reviewId
count  2.714200e+04
mean   1.628587e+07
std    3.493963e+07
min    1.705000e+03
25%    2.082886e+06
50%    2.407968e+06
75%    2.667693e+06
max    1.029234e+08
reviewId              0
creationDate          0
criticName           88
criticPageUrl        88
reviewState           0
isFresh               0
isRotten              0
isRtUrl             629
isTopCritic           0
publicationUrl        0
publicationName       0
reviewUrl          2065
quote               189
scoreSentiment        0
originalScore      7729
movieId               0
dtype: int64
0

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
from google.colab import drive
import pandas as pd
import os


drive.mount('/content/drive')


file_path = '/content/drive/MyDrive/internship/online_course_engagement_data.csv'
print(os.listdir('/content/drive/MyDrive/internship/'))


with open(file_path, 'r') as file:
    for i in range(10):
        print(file.readline())


try:
    df = pd.read_csv(file_path)
    if df.empty:
        raise ValueError("The file is empty.")
    print(df.head())
except pd.errors.EmptyDataError:
    print("No columns to parse from file")
except ValueError as ve:
    print(ve)
except Exception as e:
    print(f"An error occurred: {e}")


if 'df' in locals():

    print(df.info())
    print(df.describe())


    print(df.isnull().sum())
    df = df.dropna()


    print(df.duplicated().sum())
    df = df.drop_duplicates()



    from scipy import stats
    numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
    df = df[(np.abs(stats.zscore(df[numerical_cols])) < 3).all(axis=1)]




    cleaned_file_path = '/content/drive/MyDrive/internship/cleaned_online_course_engagement_data.csv'
    df.to_csv(cleaned_file_path, index=False)
    print("Data cleaned and saved successfully.")
else:
    print("Data cleaning skipped as the dataset could not be loaded.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['critic_reviews.csv', 'online_course_engagement_data.csv', 'second_hand_cars.csv', 'cleaned_critic_reviews.csv', 'Untitled0.ipynb']










No columns to parse from file
Data cleaning skipped as the dataset could not be loaded.